### PR TITLE
Fix append to etc hosts

### PR DESCRIPTION
**Pull request by salaun-urennes1**
No more overwrite /etc/hosts, complete it instead. This behavior it more adapted if the target host is provisioned by others means.

### CODE REVIEW

**Comment by racke** [comment]
Sounds like a good idea to me, but there is a lot of junk in the patch. Please clean up your changes.

**Comment by salaun-urennes1** [comment]
Sorry for the dirty PR.
The simplest solution for me would be to submit a new PR, if you don't mind ?

**Comment by racke** [comment]
Sure.

**Comment by salaun-urennes1** [comment]
I created a new clean PR : https://github.com/sympa-community/sympa-ansible/pull/30
I close this one

**Pull request closed without merging**
