### PR TITLE
Fix Git repository URL and branch.

### PR DESCRIPTION
**Pull request by racke**
Another fallout of the great refactoring :roll_eyes: @dverdin please review.

### CODE REVIEW

**Comment by seballot** [comment]
Thanks for the fix ! But it still not working for me with this new repo url...

```
TASK [sympa : Download sources from repository] ********************************
fatal: [local-sympa]: FAILED! => {"changed": false, "msg": "Failed to checkout branch master", "rc": 1, "stderr": "error: pathspec 'master' did not match any file(s) known to git.\n", "stderr_lines": ["error: pathspec 'master' did not match any file(s) known to git."], "stdout": "", "stdout_lines": []}
```

I tried to change repository_version from HEAD to master, but still failing, with another error

```
fatal: [local-sympa]: FAILED! => {"changed": false, "cmd": "/usr/bin/git checkout --track -b master origin/master", "msg": "Failed to checkout master", "rc": 128, "stderr": "fatal: Cannot update paths and switch to branch 'master' at the same time.\nDid you intend to checkout 'origin/master' which can not be resolved as commit?\n", "stderr_lines": ["fatal: Cannot update paths and switch to branch 'master' at the same time.", "Did you intend to checkout 'origin/master' which can not be resolved as commit?"], "stdout": "", "stdout_lines": []}
```

**Comment by racke** [comment]
It works for me. Can you try that from the commandline in the VM?

**Comment by racke** [comment]
Changed branch as well. All pull requests for Sympa should start from sympa-6.2, so we use it here as well.

**Comment by seballot** [comment]
Hi @racke !
Same error with branch sympa-6.2
```
Cannot update paths and switch to branch 'sympa-6.2' at the same time.\nDid you intend to checkout 'origin/sympa-6.2' which can not be resolved as commit?\n", "stderr_lines": ["fatal: Cannot update paths and switch to branch 'sympa-6.2' at the same time.", "Did you intend to checkout 'origin/sympa-6.2' which can not be resolved as commit?"], "stdout": "", "stdout_lines": []}
```

The command which is failing from the logs is
```
/usr/bin/git checkout --track -b sympa-6.2 origin/sympa-6
```
What do you want me to try from the VM? I tried a git clone and it works fine.
Did it works for you installing a new VM? or just updating the existing one?

**Pull request merged**
