### PR TITLE
Revert "Big changes from RENATER"

### PR DESCRIPTION
**Pull request by Olm666**
Reverts sympa-community/sympa-ansible#31

### CODE REVIEW

**Comment by dverdin** [comment]
Oh. Errrr... You read PR very quick, don't you?
What's the big deal with my PR ?

**Comment by racke** [comment]
IMHO it would be the best to completely undo the mess, even if that means a force push to master.

**Comment by dverdin** [comment]
And where the hell did my PR go?

**Comment by racke** [comment]
Amended master, so this PR is not relevant anymore.

**Comment by dverdin** [comment]
OlivierLM: You owe me a beer when we meet. ;-)

**Comment by Olm666** [comment]
Sure!  To you both…

**Pull request closed without merging**
