### PR TITLE
Do not override aliases files if they already exists on guest machine…

### PR DESCRIPTION
**Pull request by salaun-urennes1**
…. Otherwise list aliases might get lost

### CODE REVIEW

**Comment by dverdin** [comment]
That's good. however, /etc/aliases always exist on a fresh install. Consequently, we will never trigger the template generation with the current test.
I think we should use a Sympa-dedicated file for generic aliases (bounce, listmaster, etc.) that would be overwritten anytime we run the task. That way, we can enforce constraints on Sympa aliases (change a path to queue, add a domain, etc.) without breaking aliases that would have been manually added.

**Comment by racke** [comment]
It certainly makes sense to have a separate file aside from /etc/aliases.

**Comment by dverdin** [comment]
OK, I made a PR to Olivier's repository to improve his branch. If he accepts, the current PR should contain the dedicated Sympa global aliases file.

**Comment by salaun-urennes1** [comment]
I commited David's PR to use a separate sympa_global_aliases.
I also adapted playbooks to move all global sympa aliases there and have a consistant naming of files (sympa_global_aliases and sympa_list_aliases).

**Pull request merged**
