### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by salaun-urennes1**
Typos in yaml files

### CODE REVIEW

**Comment by racke** [comment]
Looks good to me, though I'm wondering how that got into the repository :zipper_mouth_face:

**Comment by dverdin** [comment]
@racke : A commit error from me. I fixed locally but forgot to commit...

**Comment by racke** [comment]
I'm going to repeat myself, but:

- keep your pull request concise and deal with **one** topic
- check local git status for forgotten files/changes
- always test it (easy with Ansible)
- always reread your changes before publishing

 It also helps the reviewer to use a proper subject, "Fixes" isn't very helpful for examples.

**Comment by dverdin** [comment]
"Teaching is the art of repeating".
Thanks for teaching me Racke! ;-)

**Pull request merged**
