### PR TITLE
Fix SSL certificate DN

### PR DESCRIPTION
**Pull request by salaun-urennes1**
The DN in environment template does not match the list server hostname: lists vs www

### CODE REVIEW

**Comment by dverdin** [comment]
Oh yes. That certificate with "www" was so wrong. It worked enough for my purpose so I did not bother to change it but you're right to fix.

Actually, I'm thinking that we could make the prefix a parameter to let users define whatever wu-domain they want.

**Comment by ikedas** [comment]
Though it is not necessary but, [Administration manual](https://sympa-community.github.io/manual/) uses mail.example.org for mail domain and web.example.org for web interface. I feel it is less astonishing for users to use uniform host names.

**Comment by racke** [comment]
Using the same domains as in the manual makes sense to me. This would be a separate issue though.

**Comment by ikedas** [comment]
@racke, I rather told about prefix.

**Comment by ikedas** [comment]
my previous post was meaningless. sorry for off-topic.

**Comment by dverdin** [comment]
Soji's post is interesting but should be put in another issue.
I'll accept the PR as it is an improvement in and for itself.
Regards,

**Pull request merged**
