### PR TITLE
Remove deprecated host and http_host settings from robot configuration

### PR DESCRIPTION
**Pull request by racke**
See also: https://github.com/sympa-community/sympa/pull/916

### CODE REVIEW

**Comment by dverdin** [comment]
Makes sense to follow the actual Sympa code.
However, I may be missing something bu why do you remove the "host" parameter, too?

**Comment by racke** [comment]
Do we really need the host parameter? Sympa should be able to derive it from the robot name.

**Comment by dverdin** [comment]
That's an interesting question. Did you try to deploy using the updated playbook?
I remember that a few minimal parameters were mandatory and I wonder whether the host wasn't amongst them.

**Comment by racke** [comment]
Seems to work for me (latest sources).

**Review by dverdin — APPROVED** [review]
In that case, no problem!
Thanks @racke!

**Pull request merged**
