### PR TITLE
Updated apache 2.4 config

### PR DESCRIPTION
**Pull request by dverdin**
Now Sympa FCGI are linked to the web server using spawnfcgi, as recommended in the Sympa documentation: https://sympa-community.github.io/manual/install/configure-http-server-spawnfcgi.html

This prepares enabling nginx as spawnfcgi is also the recommended setting for Nginx.

EDIT: I forgot to mention: Currently, when you restart Apache, the Sympa fcgi won't restart, leaving some fcgi running not linked to an Apache process, so all request are lost until you explicitely kill the fcgi processes.
Changing the way the fcgi is run fixed this problem.

### CODE REVIEW

**Comment by racke** [comment]
I would prefer to start with separating the roles in a more logical fashion. As I said: database, sympa, mail server, web server ...

Currently we have only one really top role and MySQL and Apache handlers inside Sympa handlers looks wrong to me.

**Comment by dverdin** [comment]
Yes, I agree. But I forgot to mention: this PR is also a fix.
Currently, when you restart Apache, the Sympa fcgi won't restart, leaving some fcgi running not linked to an Apache process, so all request are lost until you explicitely kill the fcgi processes.
Changing the way the fcgi is run fixed it.
But I agree with your renaming suggestion (though I'll work on it only after I have removed keyczar).

**Comment by racke** [comment]
I still feel that this is a quite big patch ... also you are using again the shell module for systemd tasks. That's wrong.

**Comment by dverdin** [comment]
Not that big... And it's atomic.
However, you're right. Using shell for systemd is wrong. I'll fix it.

**Comment by racke** [comment]
There is still a stray MySQL handler. Also the "ensure sockets directory" task is incorrect - the directory won't survive a reboot with /run and /var/run on tmpfs. Unit files can deal with needed directories.

**Comment by dverdin** [comment]
Wrong. The task might be useless but the directories are handled by the unit files. Did you look at them?

**Comment by dverdin** [comment]
The MySQL handler is in no way concerned by the web configuration. It can be dealt with in another PR.

**Comment by racke** [comment]
> The MySQL handler is in no way concerned by the web configuration. It can be dealt with in another PR.

So please remove it.

**Comment by racke** [comment]
> Wrong. The task might be useless but the directories are handled by the unit files. Did you look at them?

If the unit files take care of it, please remove the task.

**Comment by dverdin** [comment]
Let's focus. The only aim of this PR is the web configuration. I won't touch anything related to MySQL that was here before.
Please keep the rule of minimal change for a PR.

**Comment by racke** [comment]
> Let's focus. The only aim of this PR is the web configuration. I won't touch anything related to MySQL that was here before.
> Please keep the rule of minimal change for a PR.

This PR *adds* the MySQL handler :roll_eyes:

**Comment by dverdin** [comment]
Fuck. I did not notice.
OK, I remove it.

**Comment by dverdin** [comment]
Aaaaaannnd... I probably got a stupid race condition with the mysql installation... It works with a fresh environment on my machine, but not in Travis..
OK. I'll try to dumb down tomorrow and fix this.

**Comment by dverdin** [comment]
Thanks for reviewing!

**Comment by racke** [comment]
Also please use the command module instead of the shell module (see recommendations on https://docs.ansible.com/ansible/latest/modules/shell_module.html).

**Comment by dverdin** [comment]
Dully noted. I'll update the PR accordingly.

**Comment by dverdin** [comment]
OK. It was all .travis.yml fault. For some reason, I found clever to manipulate mysql activation through it.
Turns out is was not.

**Comment by dverdin** [comment]
Aaaaah... I think I addressed all the issues you raised, didn't I ? :sunglasses:

**Comment by racke** [comment]
I would expect that Apache is only restarted once after handlers.

```
RUNNING HANDLER [apache : Restart Apache] *****************************************************************************************************************************************
changed: [local-sympa]

RUNNING HANDLER [postfix : restart postfix] ***************************************************************************************************************************************
changed: [local-sympa]

RUNNING HANDLER [sympa : restart apache] ******************************************************************************************************************************************
changed: [local-sympa]
```
Why would 'Check created config' always trigger the Apache handler?

**Comment by racke** [comment]
```
root@local-sympa:/home/vagrant# systemctl status sympasoap
* sympasoap.service - SympaSOAP - SOAP interface for Sympa mailing list manager
   Loaded: loaded (/lib/systemd/system/sympasoap.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-03-07 15:34:11 CET; 14min ago
 Main PID: 8921 (sympa_soap_serv)
   CGroup: /system.slice/sympasoap.service
           |-8921 /usr/bin/perl /usr/local/sympa/bin/sympa_soap_server.fcgi
           |-8922 /usr/bin/perl /usr/local/sympa/bin/sympa_soap_server.fcgi
           |-8923 /usr/bin/perl /usr/local/sympa/bin/sympa_soap_server.fcgi
           |-8924 /usr/bin/perl /usr/local/sympa/bin/sympa_soap_server.fcgi
           `-8925 /usr/bin/perl /usr/local/sympa/bin/sympa_soap_server.fcgi

Mar 07 15:34:11 local-sympa systemd[1]: Started SympaSOAP - SOAP interface for Sympa mailing list manager.
Mar 07 15:34:18 local-sympa sympasoap[8925]: info main:: SympaSOAP started
Mar 07 15:34:18 local-sympa sympasoap[8924]: info main:: SympaSOAP started
Mar 07 15:34:18 local-sympa sympasoap[8921]: info main:: SympaSOAP started
Mar 07 15:34:18 local-sympa sympasoap[8923]: info main:: SympaSOAP started
Mar 07 15:34:18 local-sympa sympasoap[8922]: info main:: SympaSOAP started
Mar 07 15:34:23 local-sympa systemd[1]: [/lib/systemd/system/sympasoap.service:16] Unknown lvalue 'RuntimeDirectoryPreserve' in section 'Service'
Mar 07 15:37:43 local-sympa systemd[1]: [/lib/systemd/system/sympasoap.service:16] Unknown lvalue 'RuntimeDirectoryPreserve' in section 'Service'
Mar 07 15:37:44 local-sympa systemd[1]: [/lib/systemd/system/sympasoap.service:16] Unknown lvalue 'RuntimeDirectoryPreserve' in section 'Service'
Mar 07 15:37:48 local-sympa systemd[1]: [/lib/systemd/system/sympasoap.service:16] Unknown lvalue 'RuntimeDirectoryPreserve' in section 'Service'

```

**Comment by dverdin** [comment]
> Why would 'Check created config' always trigger the Apache handler?

Because the config may have been changed before.
It may  not be in the right place but as there is several places where we can change Apache config in this role we chose to restart Apache at the end, when checking the configuration.
How would you have rather do it?

**Comment by dverdin** [comment]
I don't have the same trouble with sympasoap:
```
vagrant@local-sympa:~$ systemctl status sympasoap
* sympasoap.service - SympaSOAP - SOAP interface for Sympa mailing list manager
   Loaded: loaded (/lib/systemd/system/sympasoap.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-03-07 16:39:59 CET; 5min ago
  Process: 32085 ExecStart=/usr/bin/spawn-fcgi -F $FCGI_CHILDREN -P /var/run/sympa/sympasoap.pid -u $FCGI_USER -g $FCGI_GROUP $FCGI_OPTS -- /usr/local/sympa/bin/sympa_soap_server.fcgi (code=exited, status=0/SUCCESS)
 Main PID: 32088 (sympa_soap_serv)
   CGroup: /system.slice/sympasoap.service
           |-32088 /usr/bin/perl /usr/local/sympa/bin/sympa_soap_server.fcgi
           |-32098 /usr/bin/perl /usr/local/sympa/bin/sympa_soap_server.fcgi
           |-32099 /usr/bin/perl /usr/local/sympa/bin/sympa_soap_server.fcgi
           |-32100 /usr/bin/perl /usr/local/sympa/bin/sympa_soap_server.fcgi
           `-32101 /usr/bin/perl /usr/local/sympa/bin/sympa_soap_server.fcgi
```
What version of systemd is running on your instance?
Mine is :

```
vagrant@local-sympa:~$ systemctl --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
```

**Comment by racke** [comment]
> > Why would 'Check created config' always trigger the Apache handler?
> 
> Because the config may have been changed before.
> It may not be in the right place but as there is several places where we can change Apache config in this role we chose to restart Apache at the end, when checking the configuration.
> How would you have rather do it?

I expect that we know exactly when the configuration has been changed. Also there should be only *one* handler name for restarting Apache.

**Comment by racke** [comment]
It is the same systemd version ... weird.

**Comment by dverdin** [comment]
Quick question: is it possible to define handlers in a way to make them available accross roles?
Because we need to restart Apache in several roles.

**Comment by dverdin** [comment]
Abou systemd, I don't know what can be wrong.
Are you sure you did not modify anything locally?

**Comment by racke** [comment]
> Quick question: is it possible to define handlers in a way to make them available accross roles?
> Because we need to restart Apache in several roles.

If the role is included (implicit by meta dependency or explicit by playbook), you should be able to use the handlers of these role. Also _listen_ is a nice feature for handlers - this allows multiple handlers to be notified.

**Comment by racke** [comment]
Let's ignore the systemd complaints for now.

**Comment by dverdin** [comment]
OK. I'll try to centralize the handlers in the included roles.
And, yes, let's ignore the systemd problems for now.

**Comment by dverdin** [comment]
OK. I'll try to centralize the handlers in the included roles.
And, yes, let's ignore the systemd problems for now.

**Comment by dverdin** [comment]
Hey, Étienne figured out the systemd thing!
Actually, when wwsympa restarts, it destroys any sympasoap.pid and sympasoap.socket. sympasoap does the same for wwsympa.
turns out the "preserve" directives we put in the systemd files only preserve the directory, not its content.
Étienne is working on a fix that I'll commit here after.

EDIT: Typos.

**Comment by racke** [comment]
Finally good to go. Thanks @dverdin.

**Comment by dverdin** [comment]
Yay! I'm valuable! :smile: 
Thanks Racke!

**Pull request merged**
