### PR TITLE
Optional antispam

### PR DESCRIPTION
**Pull request by dverdin**
Adding optional Spamassassin on the Sympa server.

### CODE REVIEW

**Comment by racke** [comment]
Good idea, but Spamassassin should *really* get his own role !!!

**Comment by dverdin** [comment]
You're right. It should not be a sub-role of postfix...
I'll try to fix this!

**Comment by racke** [comment]
Please get rid of debug tasks. Also the modifications to the postfix configuration file belong into the postfix role.

**Comment by dverdin** [comment]
Not sure about Postifx. If we try to rely on Galaxy role, we won't modify these roles, won't we? 
So I think the Sympa role should handle the modifications that concern itself only.

**Comment by racke** [comment]
We can just wrap the Galaxy postfix role inside our own postfix role, so we can add tasks for spamassassin in that postfix role:

```
- name: Run external Postfix role
  include_role:
     name: nevairbe.postfix

- name: Add config for Spamassassin
  ....
  notify: Restart postfix (from the Galaxy role)
```

That has also the benefit that we can override role defaults here and not in the playbook.

**Comment by dverdin** [comment]
Oh, OK then.

**Comment by racke** [comment]
Repository is obsolete.

**Comment by racke** [comment]
Repository is obsolete.

**Pull request closed without merging**
