### PR TITLE
Pick service according to current database type.

### PR DESCRIPTION
**Pull request by racke**
Also change status for systemd task to restarted in case of changes in
the sympa.service.d dropin directory.

### CODE REVIEW

**Comment by dverdin** [comment]
Very good idea. Do you think something like this could be usefull?
in `roles/sympa/templates/systemd/custom.conf.j2` :
```
Requires={% sympa.db.service_name  %}.service
```

in `roles/sympa/defaults/main.yml` :

```
sympa:
  db:
    type: Pg
    service_name: postgresql
```

**Comment by racke** [comment]
I would rather add a task that sets the service name based on the type and checks that the type is valid.

**Comment by dverdin** [comment]
Ok, so I think this is a later improvement. Let's validate this PR as is and improve it after (if needed).
Shall we?

**Comment by racke** [comment]
OK, let's merge it.

**Pull request merged**
